services:

  backend-issues:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
      - "5173:5173" 
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-issues
    environment:
      STRAPI_TELEMETRY_DISABLED: "true"
    env_file: backend/.env
    networks:
      - issues_network

  frontend-issues:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    env_file: frontend/.env
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - issues_network

  db-issues:
    image: postgres:17.4
    volumes:
      - postgres_issues_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - issues_network

volumes:
  postgres_issues_data:

networks:
  issues_network:
    driver: bridge